function SideColEndTopicStats ({data}) {
    return(
        <div id="side-col-end-topic" className="side-col-end">
            <h1>Topic Stats</h1>
            <table>
                <thead>
                    <tr>
                        <td>topic_title</td>
                        <td>nberPost</td>
                        <td>status</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>topic_title</td>
                        <td>nberPost</td>
                        <td>status</td>
                    </tr>
                    <tr>
                        <td>topic_title</td>
                        <td>nberPost</td>
                        <td>status</td>
                    </tr>
                    <tr>
                        <td>topic_title</td>
                        <td>nberPost</td>
                        <td>status</td>
                    </tr>
                    <tr>
                        <td>topic_title</td>
                        <td>nberPost</td>
                        <td>status</td>
                    </tr>
                    <tr>
                        <td>topic_title</td>
                        <td>nberPost</td>
                        <td>status</td>
                    </tr>
                    <tr>
                        <td>topic_title</td>
                        <td>nberPost</td>
                        <td>status</td>
                    </tr>
                    <tr>
                        <td>topic_title</td>
                        <td>nberPost</td>
                        <td>status</td>
                    </tr>
                    <tr>
                        <td>topic_title</td>
                        <td>nberPost</td>
                        <td>status</td>
                    </tr>
                </tbody>
            </table>
        </div>
    )
}

export default SideColEndTopicStats